### ISSUE TITLE
Azer did not make the right call

### ISSUE THREAD

**Issue by atticoos** [Kriegslustig/kikgate#1]
[README describes Azer to have made the correct call](https://github.com/Kriegslustig/kikgate/commit/8a3d53c6835ce60ab1e53a6003507461dbeb45a5#diff-04c6e90faac2675aa89e2176d2eec7d8R3). But he didn't, plz fix

:trolleybus: :trollface:

**Comment by halbgut** [comment]
@ajwhite hahah! :grin: 

Pro:
- What Npm Inc. did was wrong and he had to show them, that they couldn't just pull shit like that off
- He got the attention of the community to two huge problems
  - `npm unpublish` breaks dependencies
  - The removed package names can be taken over by malicious actors, they now have (pretty much) total control of any dependents' machines 

Con:
- It made the Npm ecosystem looks unstable

Pro wins IMO. What do you think?

**Comment by atticoos** [comment]
:bell: :bell:  we have a winner! :tada:

**Comment by atticoos** [comment]
:joy:
